### ISSUE TITLE
Getting things up and running is just confusing.

### ISSUE THREAD

**Issue by minitech** [EliW/treb#3]
I still can't figure it out entirely; it keeps thinking I'm hijacking the session. (Haven't changed _anything_ except added the `config.xml` file and created the `/tmp/session` directory.)

Perhaps a short tutorial would help?

**Comment by EliW** [comment]
Sorry about that.  Given this was a very quick cleanup, there are very possibly a number of things missing as far as "What you need to do"

So what error are you actually getting?   Or are you just seeing it redirect you to home constantly and you see the hijack log growing?

**Comment by minitech** [comment]
The first time I visit the home page, it gives me a 404 - but if I refresh, it counts it as a session hijack and redirects to `/`. (Is it a side-effect of the path being `/treb` as opposed to `/`?)

**Comment by EliW** [comment]
Ah, yes.   treb, as written right now, wants to completely take over your domain.    So whatever domain you are serving it under, it needs to be the '/' of it.    You can test this locally by just serving it up as some "mydomain.local" (and add it to your hosts files) ...

It's probably possible to tweak treb's understanding of where it lives, so that it could live as subdir.  But currently it wants to own the domain it lives on.

**Comment by EliW** [comment]
Closing this down for now, if you still have any issues please reach out!
